# Use official Python image
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy requirements.txt first to install dependencies separately
COPY requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the Locust code
COPY . .

# Expose Locust web UI port
EXPOSE 8089

# Default command to run Locust
ENV LOCUST_HOST http://localhost:9091
CMD ["sh", "-c", "locust -f locustfile.py --host $LOCUST_HOST --web-port 8089"]