# Use official Python image
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy requirements.txt first to install dependencies separately
COPY requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the Locust code
COPY . .

# Expose Locust web UI port
EXPOSE 8089

# Default command to run Locust
CMD ["locust", "-f", "locustfile.py", "--host", "http://13.60.37.78:9091", "--web-port", "8089"]